# --- CONEXÃO E PERIFÉRICOS ---
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# --- GERENCIAMENTO DE ENERGIA ---
CONFIG_ZMK_SLEEP=n
CONFIG_ZMK_EXT_POWER=y

# Define o tempo de inatividade para apagar a tela (1 hora)
CONFIG_ZMK_IDLE_TIMEOUT=3600000

# --- CONFIGURAÇÕES DO DISPLAY ---
CONFIG_ZMK_DISPLAY=y

# Removida a linha que impedia o desligamento para que o timeout acima funcione

# Configurações específicas para o dongle e bateria dos periféricos
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_DONGLE_DISPLAY_DONGLE_BATTERY=n
CONFIG_BT_BAS=n
CONFIG_ZMK_DONGLE_DISPLAY_LAYER_TEXT_ALIGN="center" 

# --- BLUETOOTH E HID ---
CONFIG_ZMK_BLE_PASSKEY_ENTRY=n
CONFIG_ZMK_BLE_CLEAR_BONDS_ON_START=n
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=n
