# Melhora a estabilidade da conexão BLE (Essencial para Dongles)
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# Gerenciamento de Energia
# Teste com 'n' primeiro. Se a bateria durar pouco, mudamos para 'y' com um tempo maior.
CONFIG_ZMK_SLEEP=n

# Tempo de Idle (apenas apaga os LEDs/OLED se houver, sem desligar o rádio)
# 900000 ms = 15 minutos
CONFIG_ZMK_IDLE_TIMEOUT=900000

# Mantém o gerenciamento de energia do hardware ativo
CONFIG_PM_DEVICE=y

# Se você não usa RGB ou OLED, pode manter como 'y' ou 'n', 
# mas se tiver, 'y' ajuda a economizar nos pinos externos.
CONFIG_ZMK_EXT_POWER=y
