# --- CONEXÃO E PERIFÉRICOS ---
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# --- GERENCIAMENTO DE ENERGIA ---
# Desativa o Deep Sleep e mantém o Ext Power ativo para o Display
CONFIG_ZMK_SLEEP=n
CONFIG_ZMK_EXT_POWER=y

# --- CONFIGURAÇÕES DO DISPLAY ---
CONFIG_ZMK_DISPLAY=y

# 1. Resolve o problema de apagar rápido: 
# Desativa o "blanking" automático da tela quando ocioso
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=n

# 2. Resolve o problema de não mostrar a Layer:
# Força a exibição do widget de Layer e status
CONFIG_ZMK_WIDGET_LAYER_STATUS=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS=y
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y

# 3. Configurações de bateria dos lados (Periféricos)
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_DONGLE_DISPLAY_DONGLE_BATTERY=y
CONFIG_BT_BAS=n

# --- BLUETOOTH E HID ---
CONFIG_ZMK_BLE_PASSKEY_ENTRY=n
CONFIG_ZMK_BLE_CLEAR_BONDS_ON_START=n
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=n
